### ISSUE TITLE
jQuery(...).getSize is not a function + alerts('Что-то пошло не так')

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#205]
Здравствуйте! Скажите пожалуйста, после обновления на 1.3.4 при открытии страниц админ-панели появляются множество alert ('Что-то пошло не так') + в консоли jQuery(...).getSize is not a function
На странице подключено 2 jquery (3.1.0 3.1.1), видимо конфликт из-за этого.

_______________________________

Hello! Tell me please, after updating to 1.3.4 when opening pages in the admin panel appear a lot of alert ('something went wrong') + console jQuery(...).getSize is not a function
2 connected jquery (3.1.0 3.1.1), apparently a conflict because of this.

![2017-08-31_10-26-46](https://user-images.githubusercontent.com/3595562/29911575-126d408c-8e37-11e7-99ae-7f44044ca15f.png)
![2017-08-31_10-27-03](https://user-images.githubusercontent.com/3595562/29911576-126d7e9e-8e37-11e7-8088-3770ef58a270.png)

**Comment by sazanof** [comment]
дубль в плагине EVO.keybinds
